dist: trusty
language: node_js
node_js:
- stable
script:
- npm run coverage_cosmetic
- npm run coverage_customer
after_success:
- npm run publish-coverage
branches:
 only: master
notifications:
 email:
    recipients:
    - 425765498@qq.com
    on_success: never        
    on_failure: always